Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
Traceback (most recent call last):
  File "pytorch/main_pretrained.py", line 12, in <module>
    from benchmark import PyTorchBenchmark
  File "/home/jaredfer/Projects/DeviceBenchmarking/pytorch/benchmark.py", line 6, in <module>
    import intel_extension_for_pytorch as ipex
ModuleNotFoundError: No module named 'intel_extension_for_pytorch'
